service: rimac-nest-serverless

provider:
  name: aws
  runtime: nodejs18.x
  profile: default
  region: us-east-1
  stage: production
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
    NODE_PORT: 3000

    AWS_S3_BUCKET: hola
    AWS_DYNAMO_TABLE: AppointmentTable

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-jetpack
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!node_modules/aws-sdk/**'
    - '!test/**'
    - '!**/*.spec.ts'

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    useChildProcesses: true

resources:
  Resources:
    AppointmentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentTable
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
